@extends('User.layout.main')
@section('content')
@include('User.home.banner')
@include('User.home.newproducts')
@include('User.home.topproducts')
@include('User.home.salesproducts')
@include('User.home.products')
@include('User.home.modal')
@endsection
